name: Monthly Operations Tasks
on: workflow_dispatch

jobs:
  create_issue:
    name: Monthly Operations Issue
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Monthly Operations Issue
        run: |
          if [[ $CLOSE_PREVIOUS == true ]]; then
            previous_issue_number=$(gh issue list \
              --label "$LABELS" \
              --json number \
              --jq '.[0].number')
            if [[ -n $previous_issue_number ]]; then
              gh issue close "$previous_issue_number"
              gh issue unpin "$previous_issue_number"
            fi
          fi
          new_issue_url=$(gh issue create \
            --title "$TITLE" \
            --assignee "$ASSIGNEES" \
            --label "$LABELS" \
            --body "$BODY")
          if [[ $PINNED == true ]]; then
            gh issue pin "$new_issue_url"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          TITLE: Monthly Issue
          ASSIGNEES: pawalker99
          LABELS: monthly,operations
          BODY: |
            ### To Do

            - [ ] Start the recording
            - [ ] Check-ins
            - [ ] Discussion points
            - [ ] Post the recording

          PINNED: false
          CLOSE_PREVIOUS: false
